build:
    zip:
        pack:
            excludes:
                paths:
                    - .gitignore
                    - release
                    - phpcs.xml
                    - phpunit.xml.dist
                    - vendor/findologic/shopware6-common/.git
                    - "*.zip"
                    - "*.phar"
