name: Lint JS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
        shopware-versions: [
          '6.5.5.1',
        ]

    name: ESLint - ${{ matrix.shopware-versions }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/echo.yml

      - name: Validate dependencies
        run: |
          cd plugin-shopware-6
          composer validate

      - name: Create shop
        run: shopware-cli project create shopware ${{ matrix.shopware-versions }}

      - name: Install Shopware
        run: |
          cp plugin-shopware-6/.github/.env.local shopware
          cp plugin-shopware-6/.github/.env.test shopware
          cd shopware
          ./bin/console system:install --basic-setup

      - name: Install administration dependencies
        run: |
          cd shopware/vendor/shopware/administration/Resources/app/administration
          npm i

      - name: Install storefront dependencies
        run: |
          cd shopware/vendor/shopware/storefront/Resources/app/storefront
          npm i

      - name: Install dependencies
        run: |
          cd plugin-shopware-6
          composer install --no-interaction
          npm i
          cd src/Resources/app/storefront
          npm ci

      - name: Install Plugin
        run: |
          mv plugin-shopware-6 shopware/custom/plugins
          cd shopware
          php bin/console plugin:refresh
          php bin/console plugin:install --activate --clearCache FinSearch
          ./bin/build-administration.sh
          ./bin/build-storefront.sh

      - name: Run ESLint
        run: |
          cd shopware/custom/plugins/plugin-shopware-6
          make administration-lint
          make storefront-lint
