# Used for Shopware versions < 6.4
name: PHPUnit-Legacy

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        shopware-versions: ['6.2', 'v6.3.2.1', 'v6.3.5.3']

    name: Shopware ${{ matrix.shopware-versions }} Test (PHP ${{ matrix.php-versions }})
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: shopware
          mysql root password: shopware

      - uses: actions/checkout@v2
        with:
          path: plugin-shopware-6

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, gd, mbstring, pdo_mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        run: |
          cd plugin-shopware-6
          composer validate

      - name: Clone Shopware repository
        uses: actions/checkout@v2
        with:
          repository: shopware/development
          ref: ${{ matrix.shopware-versions }}
          path: development

      - name: Install Shopware
        run: |
          cp plugin-shopware-6/.github/.psh.yaml.override development
          cd development
          ./psh.phar init

      - name: Install Plugin dependencies
        run: |
          cd plugin-shopware-6
          composer install --no-interaction

      - name: Install Plugin
        run: |
          mv plugin-shopware-6 development/custom/plugins
          cd development
          php bin/console plugin:refresh
          php bin/console plugin:install --activate --clearCache FinSearch

      # Deprecation Helper disabled until the final release of 6.4.
      - name: Run test suite
        run: |
          cd development/custom/plugins/plugin-shopware-6
          SYMFONY_DEPRECATIONS_HELPER=disabled composer test-legacy
