# Automatically uploads the pushed plugin version to the Shopware Store.

name: Shopware Store Release
on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: FinSearch
  ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
  ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
  PLUGIN_UPLOADER_VERSION: 0.3.11

jobs:
  validatePlugin:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, dom
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Download plugin uploader
        run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

      - name: Build Plugin Relase-Zipfile
        run: composer build-release

      - name: Validate Plugin Release-Zipfile
        run: php frosh-plugin-upload.phar ext:validate $(pwd)/${PLUGIN_NAME}.zip

  storeRelease:
    if: startsWith(github.ref, 'refs/tags/')
    needs: validatePlugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, dom
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Download plugin uploader
        run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

      - name: Build Plugin Relase-Zipfile
        run: composer build-release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          bodyFile: 'docs/release/body.md'

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip

#      - name: Upload Plugin to Shopware Store
#        run: php frosh-plugin-upload.phar ext:upload $(pwd)/${PLUGIN_NAME}.zip
